@extends('layouts.Search')
@section('tit','用户列表')
@section('table')
    <table class="table">
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>微博数量</th>
            <th>手机号</th>
            <th>Email</th>
            <th>注册时间</th>
            <th>操作</th>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
    @endsection