@extends('admin.classify')
@section('title','微博分类')
@section('tit','微博分类')
@section('table')
    <table class="table">
       <tr>
           <th>ID</th>
           <th>分类名称</th>
           <th>微博数量</th>
           <th>操作</th>
       </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
    @endsection