@extends('layouts.List')
@section('title','转发微博')
@section('tit','转发微博')
@section('table')
    <table class="table">
        <tr>
            <th>ID</th>
            <th>原微博</th>
            <th>转发作者</th>
            <th>转发时间</th>
            <th>点赞数</th>
            <th>评论数</th>
            <th>操作</th>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
@endsection